server:
  port: 8088

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true   #该配置开启后，服务名可以小写
  #是否与服务注册于发现组件进行结合,
  #设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    appname: gateway-server
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
