server:
  port: 8763
spring:
  application:
    name: wechat-server
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
  zipkin:
    base-url: http://localhost:8700
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web # 设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1 # 1代表抓取100%的日志
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    appname: wechat-server
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
