server:
  port: 8769
spring:
  application:
    name: client-file
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    appname: client-file
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

