server:
  port: 8762
spring:
  application:
    name: client-user
  mvc:
    throw-exception-if-no-handler-found: true  # 出现错误时，直接抛出异常
  resources:
    add-mappings: false # 不与资源文件建立映射关系
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    appname: client-user
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
