server:
  port: 8762
spring:
  application:
    name: client-user
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    appname: client-user
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
